package main

import (
	"time"

	"github.com/mstrYoda/maasanketi.co/domain/survey"
)

func DefaultSurvey() *survey.Survey {
	createdBy := "MaaşAnketi.co"
	// Set finishes_at to 3 months from now
	finishesAt := time.Now().AddDate(0, 3, 0)
	return &survey.Survey{
		Title:                "Software Engineer Salary Survey",
		Description:          "This survey collects anonymous data about software engineer salaries and working conditions.",
		MinCompletionTimeMin: 3, // Minimum 3 minutes to complete the survey
		CreatedBy:            &createdBy,
		Tags:                 []string{"software", "engineering", "salary"},
		FinishesAt:           &finishesAt,
		Questions: []survey.Question{
			{
				ID:       "employment_type",
				Text:     "What is your employment type?",
				Type:     survey.QuestionTypeSelect,
				Required: true,
				Order:    1,
				Options: []survey.Option{
					{ID: "full_time", Value: "Full-time employee"},
					{ID: "part_time", Value: "Part-time employee"},
					{ID: "freelancer", Value: "Freelancer/Contractor"},
					{ID: "other", Value: "Other"},
				},
			},
			{
				ID:          "salary",
				Text:        "What is your annual salary in your local currency?",
				Type:        survey.QuestionTypeNumber,
				Required:    true,
				Order:       2,
				Placeholder: "e.g., 100000",
				Conditional: &survey.Conditional{
					QuestionID: "employment_type",
					Value:      "full_time,part_time",
				},
			},
			{
				ID:          "freelance_rate",
				Text:        "What is your hourly rate in your local currency?",
				Type:        survey.QuestionTypeNumber,
				Required:    true,
				Order:       3,
				Placeholder: "e.g., 100",
				Conditional: &survey.Conditional{
					QuestionID: "employment_type",
					Value:      "freelancer",
				},
			},
			{
				ID:       "currency",
				Text:     "What currency are you paid in?",
				Type:     survey.QuestionTypeSelect,
				Required: true,
				Order:    4,
				Options: []survey.Option{
					{ID: "usd", Value: "USD"},
					{ID: "eur", Value: "EUR"},
					{ID: "gbp", Value: "GBP"},
					{ID: "try", Value: "TRY"},
					// Add more currencies as needed
				},
			},
			{
				ID:          "job_title",
				Text:        "What is your job title?",
				Type:        survey.QuestionTypeText,
				Required:    true,
				Order:       5,
				Placeholder: "e.g., Senior Software Engineer",
			},
			{
				ID:          "total_experience",
				Text:        "How many years of total professional experience do you have?",
				Type:        survey.QuestionTypeNumber,
				Required:    true,
				Order:       6,
				Placeholder: "e.g., 5",
			},
			{
				ID:          "company_experience",
				Text:        "How many years have you been with your current company?",
				Type:        survey.QuestionTypeNumber,
				Required:    true,
				Order:       7,
				Placeholder: "e.g., 2",
			},
			{
				ID:          "it_department_size",
				Text:        "How many employees are in your IT/Engineering department?",
				Type:        survey.QuestionTypeSelect,
				Required:    true,
				Order:       8,
				Placeholder: "Select a range",
				Options: []survey.Option{
					{ID: "1-10", Value: "1-10"},
					{ID: "11-50", Value: "11-50"},
					{ID: "51-200", Value: "51-200"},
					{ID: "201-1000", Value: "201-1000"},
					{ID: "1001+", Value: "1001+"},
					{ID: "unknown", Value: "I don't know"},
				},
			},
			{
				ID:          "company_size",
				Text:        "How many employees are in your company overall?",
				Type:        survey.QuestionTypeSelect,
				Required:    true,
				Order:       9,
				Placeholder: "Select a range",
				Options: []survey.Option{
					{ID: "1-10", Value: "1-10"},
					{ID: "11-50", Value: "11-50"},
					{ID: "51-200", Value: "51-200"},
					{ID: "201-1000", Value: "201-1000"},
					{ID: "1001-2500", Value: "1001-2500"},
					{ID: "2501+", Value: "2501+"},
					{ID: "unknown", Value: "I don't know"},
				},
			},
			{
				ID:          "company_type",
				Text:        "What type of company do you work for?",
				Type:        survey.QuestionTypeSelect,
				Required:    true,
				Order:       10,
				Placeholder: "Select company type",
				Options: []survey.Option{
					{ID: "corporate", Value: "Corporate/Enterprise"},
					{ID: "startup", Value: "Startup"},
					{ID: "small_business", Value: "Small Business"},
					{ID: "family_owned", Value: "Family-owned Business"},
					{ID: "government", Value: "Government/Public Sector"},
					{ID: "nonprofit", Value: "Non-profit"},
					{ID: "other", Value: "Other"},
				},
			},
			{
				ID:          "company_sector",
				Text:        "What sector does your company operate in?",
				Type:        survey.QuestionTypeSelect,
				Required:    true,
				Order:       11,
				Placeholder: "Select sector",
				Options: []survey.Option{
					{ID: "tech", Value: "Technology/Software"},
					{ID: "finance", Value: "Finance/Banking"},
					{ID: "healthcare", Value: "Healthcare"},
					{ID: "education", Value: "Education"},
					{ID: "ecommerce", Value: "E-commerce/Retail"},
					{ID: "manufacturing", Value: "Manufacturing"},
					{ID: "media", Value: "Media/Entertainment"},
					{ID: "agency", Value: "Agency/Consulting"},
					{ID: "telecom", Value: "Telecommunications"},
					{ID: "other", Value: "Other"},
				},
			},
			{
				ID:          "salary_increase",
				Text:        "What was your latest salary increase rate (percentage)?",
				Type:        survey.QuestionTypeNumber,
				Required:    false,
				Order:       12,
				Placeholder: "e.g., 10",
			},
			{
				ID:       "education",
				Text:     "What is your highest level of education?",
				Type:     survey.QuestionTypeSelect,
				Required: true,
				Order:    13,
				Options: []survey.Option{
					{ID: "high_school", Value: "High School"},
					{ID: "associate", Value: "Associate's Degree"},
					{ID: "bachelor", Value: "Bachelor's Degree"},
					{ID: "master", Value: "Master's Degree"},
					{ID: "phd", Value: "PhD or Doctorate"},
					{ID: "self_taught", Value: "Self-taught"},
					{ID: "bootcamp", Value: "Bootcamp"},
					{ID: "other", Value: "Other"},
				},
			},
			{
				ID:          "tech_stack",
				Text:        "What are your primary technologies/programming languages?",
				Type:        survey.QuestionTypeMultiSelect,
				Required:    true,
				Order:       14,
				Placeholder: "Select all that apply",
				Options: []survey.Option{
					{ID: "javascript", Value: "JavaScript"},
					{ID: "typescript", Value: "TypeScript"},
					{ID: "python", Value: "Python"},
					{ID: "java", Value: "Java"},
					{ID: "csharp", Value: "C#"},
					{ID: "cpp", Value: "C++"},
					{ID: "go", Value: "Go"},
					{ID: "rust", Value: "Rust"},
					{ID: "php", Value: "PHP"},
					{ID: "ruby", Value: "Ruby"},
					{ID: "swift", Value: "Swift"},
					{ID: "kotlin", Value: "Kotlin"},
					{ID: "scala", Value: "Scala"},
					{ID: "react", Value: "React"},
					{ID: "angular", Value: "Angular"},
					{ID: "vue", Value: "Vue.js"},
					{ID: "node", Value: "Node.js"},
					{ID: "dotnet", Value: ".NET"},
					{ID: "spring", Value: "Spring"},
					{ID: "django", Value: "Django"},
					{ID: "rails", Value: "Ruby on Rails"},
					{ID: "laravel", Value: "Laravel"},
					{ID: "aws", Value: "AWS"},
					{ID: "azure", Value: "Azure"},
					{ID: "gcp", Value: "Google Cloud"},
					{ID: "docker", Value: "Docker"},
					{ID: "kubernetes", Value: "Kubernetes"},
					{ID: "other", Value: "Other"},
				},
			},
			{
				ID:       "living_country",
				Text:     "In which country do you live?",
				Type:     survey.QuestionTypeText,
				Required: true,
				Order:    15,
			},
			{
				ID:       "living_city",
				Text:     "In which city do you live?",
				Type:     survey.QuestionTypeText,
				Required: true,
				Order:    16,
			},
			{
				ID:       "working_country",
				Text:     "In which country is your employer/client based?",
				Type:     survey.QuestionTypeText,
				Required: true,
				Order:    17,
			},
			{
				ID:       "working_city",
				Text:     "In which city is your employer/client based?",
				Type:     survey.QuestionTypeText,
				Required: true,
				Order:    18,
			},
			{
				ID:       "remote_work",
				Text:     "What is your work arrangement?",
				Type:     survey.QuestionTypeSelect,
				Required: true,
				Order:    19,
				Options: []survey.Option{
					{ID: "fully_remote", Value: "Fully remote"},
					{ID: "hybrid", Value: "Hybrid (partially remote)"},
					{ID: "onsite", Value: "Fully onsite"},
				},
			},
		},
	}
}
