// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.maasanketi.co/support",
            "email": "support@maasanketi.co"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "View the profile of the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "View user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.UserProfile"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "get the status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HealthCheck"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/surveys": {
            "get": {
                "description": "List all available surveys with pagination, filtering, and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "surveys"
                ],
                "summary": "List all surveys with pagination and filtering",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by tag",
                        "name": "tag",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (created_at_asc, created_at_desc, most_participants, finishes_at_asc, finishes_at_desc)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Hide expired surveys",
                        "name": "hideExpired",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Text search query for title and description",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SurveyListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/surveys/{slug}": {
            "get": {
                "description": "Get a survey by its Slug",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "surveys"
                ],
                "summary": "Get a survey by Slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Survey Slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/survey.Survey"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/surveys/{slug}/responses": {
            "post": {
                "description": "Start a new response for a survey",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "survey-responses"
                ],
                "summary": "Start a new survey response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Survey Slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Is Anonymous",
                        "name": "isAnonymous",
                        "in": "body",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ViewDefault"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/surveys/{slug}/responses/{responseId}": {
            "patch": {
                "description": "Complete a survey response with the provided data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "survey-responses"
                ],
                "summary": "Complete a survey response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Survey Slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Response ID",
                        "name": "responseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Response data",
                        "name": "response",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ResponseCompleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ViewDefault"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/surveys/{slug}/results": {
            "get": {
                "description": "List all survey results",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "survey-results"
                ],
                "summary": "List all survey results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Survey Slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resgraph.ViewList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ResponseCompleteRequest": {
            "type": "object",
            "required": [
                "answers",
                "responseID",
                "slug"
            ],
            "properties": {
                "answers": {
                    "type": "object",
                    "additionalProperties": true
                },
                "responseID": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "SurveyListResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/survey.ViewList"
                    }
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "graph.Kind": {
            "type": "string",
            "enum": [
                "bar",
                "line",
                "radar",
                "area",
                "scatter",
                "pie"
            ],
            "x-enum-varnames": [
                "KindBar",
                "KindLine",
                "KindRadar",
                "KindArea",
                "KindScatter",
                "KindPie"
            ]
        },
        "handler.UserProfile": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                }
            }
        },
        "resgraph.ResponseGraphContent": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "resgraph.ViewList": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resgraph.ResponseGraphContent"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "graphId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "$ref": "#/definitions/graph.Kind"
                },
                "surveyId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "response.Answers": {
            "type": "object",
            "additionalProperties": true
        },
        "response.ViewDefault": {
            "type": "object",
            "properties": {
                "answers": {
                    "$ref": "#/definitions/response.Answers"
                },
                "id": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "surveyId": {
                    "type": "string"
                }
            }
        },
        "survey.Conditional": {
            "type": "object",
            "properties": {
                "questionId": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "survey.Option": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "survey.Question": {
            "type": "object",
            "properties": {
                "conditional": {
                    "$ref": "#/definitions/survey.Conditional"
                },
                "id": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/survey.Option"
                    }
                },
                "order": {
                    "type": "integer"
                },
                "placeholder": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/survey.QuestionType"
                }
            }
        },
        "survey.QuestionType": {
            "type": "string",
            "enum": [
                "text",
                "number",
                "select",
                "multi-select",
                "boolean"
            ],
            "x-enum-varnames": [
                "QuestionTypeText",
                "QuestionTypeNumber",
                "QuestionTypeSelect",
                "QuestionTypeMultiSelect",
                "QuestionTypeBoolean"
            ]
        },
        "survey.Survey": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "description": "Optional creator name",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "finishesAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "minCompletionTimeMin": {
                    "description": "Minimum completion time in minutes",
                    "type": "integer"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/survey.Question"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "description": "Optional tags for categorization",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "survey.ViewList": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "finishesAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isExpired": {
                    "type": "boolean"
                },
                "minCompletionTimeMin": {
                    "type": "integer"
                },
                "participants": {
                    "description": "Number of completed responses",
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the ID token",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4004",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Maasanketi API",
	Description:      "API for the Maasanketi platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
